Check for global flag when setting up common SSH

diff --git a/common-setup/bashrc b/common-setup/bashrc
--- a/common-setup/bashrc
+++ b/common-setup/bashrc
@@ -76,22 +76,28 @@ set_prompt(){
 # Now set it. If any of these colors are later overridden, then just rerun `set_prompt`
 set_prompt
 
-# Start ssh-agent
-# This somehow started failing on OS X at some time, as `ssh-add -l`
-# never exits with status 2, always 1
-# The fix on OS X is simply to add the keys using the keychain like this: `ssh-add -K`
-# Unsafe on shared machines: http://rabexc.org/posts/pitfalls-of-ssh-agents
-ssh-add -l &>/dev/null
-if [ "$?" == 2 ]; then
-  test -r ~/.ssh-agent && \
-    eval "$(<~/.ssh-agent)" >/dev/null
+function _setup-ssh-agent(){
+    # Start ssh-agent
+    # This somehow started failing on OS X at some time, as `ssh-add -l`
+    # never exits with status 2, always 1
+    # The fix on OS X is simply to add the keys using the keychain like this: `ssh-add -K`
+    # Unsafe on shared machines: http://rabexc.org/posts/pitfalls-of-ssh-agents
+    ssh-add -l &>/dev/null
+    if [ "$?" == 2 ]; then
+        test -r ~/.ssh-agent && \
+            eval "$(<~/.ssh-agent)" >/dev/null
 
-  ssh-add -l &>/dev/null
-  if [ "$?" == 2 ]; then
-    (umask 066; ssh-agent > ~/.ssh-agent)
-    eval "$(<~/.ssh-agent)" >/dev/null
-    ssh-add
-  fi
+        ssh-add -l &>/dev/null
+        if [ "$?" == 2 ]; then
+            (umask 066; ssh-agent > ~/.ssh-agent)
+            eval "$(<~/.ssh-agent)" >/dev/null
+            ssh-add
+        fi
+    fi
+}
+
+if [[ "$NO_RUN_SSH_AGENT" != "true" ]]; then
+    _setup-ssh-agent
 fi
 
 
