Update git-delete-merged to use EasyOptions parser

diff --git a/utils/scripts/git-delete-merged b/utils/scripts/git-delete-merged
--- a/utils/scripts/git-delete-merged
+++ b/utils/scripts/git-delete-merged
@@ -8,27 +8,30 @@ fi
 
 SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 source $SCRIPT_DIR/cross-platform-utils.bashlib
+source $SCRIPT_DIR/easyoptions.sh
 DRY_RUN=1
 
-usage(){
-    echo 'git-delete-merged [--doit] <[--local] | <remote>> [<branches to skip>]'
-    echo
-    echo 'Example: git-delete-merged --doit origin deploy-branch,demo'
-    echo
-    echo 'By default, "master" and "develop" are skipped'
-    echo 'Specifying core.protected-branches in your git config, or'
-    echo 'listing them on the command line with commas will override this'
-}
+##  Usage: @script.name [--doit] <[--local] | --remote <remote>> [--branches-to-skip <branches to skip>]
+## 
+##  Example: git-delete-merged --doit origin deploy-branch,demo
+## 
+##  By default, "master" and "develop" are skipped
+##  Specifying core.protected-branches in your git config, or
+##  listing them on the command line with commas will override this
+## 
+##  Options:
+##      -d, --doit              Execute the plan. 
+##      -l, --local             Operate on local branches
+##      --remote=my-remote      Operate on remote branches on the remote repo
+##      --skip=branches         The list of branches to skip. Default is "master,develop"
 
-# @args: <origin|--local> branch1 branch2 branch-to-keep ...
-# @returns branch1 branch2
 skipped(){
     default='master,develop'
     override="$(git config --get core.protected-branches)"
 
     # command line args trumps git config
-    if [[ x$2 != x ]]; then
-        override=$2
+    if [[ -n $skip ]]; then
+        override=$skip
     fi
 
     if [[ x$override != x ]]; then
@@ -45,34 +48,33 @@ print-branches(){
 }
 
 main(){
-    if [[ $1 == "--doit" ]];then
-        shift
+    if [[ -n $doit ]];then
         DRY_RUN=0
     fi
 
     no_branches_msg="No branches to delete"
     delete_branches_msg="Deleting the following branches"
 
-    if [[ $1 == "--local" ]];then
+    if [[ -n $local ]];then
         branches=$(
                     git branch --merged \
                     | util.esed -n 's/..(.*)/\1/p' \
                     | egrep -v \
-                        "$(skipped $@ | util.esed -e 's/,/|/g' -e 's/(\w+)/^\1$/g' )" \
+                        "$(skipped $skip | util.esed -e 's/,/|/g' -e 's/(\w+)/^\1$/g' )" \
                     | paste -s
                 )
 
     else 
         branches=$(
                     git branch -r --merged \
-                    | grep "  $1"  \
+                    | grep "  $remote"  \
                     | util.esed -n 's/  \w*\/(.*)/\1/p' \
                     | egrep -v \
-                        "$(skipped $@ | util.esed -e 's/,/|/g' -e 's/(\w+)/^\1$/g' )" \
+                        "$(skipped $skip | util.esed -e 's/,/|/g' -e 's/(\w+)/^\1$/g' )" \
                     | paste -s
                 )
-        no_branches_msg="${no_branches_msg} on $1"
-        delete_branches_msg="${delete_branches_msg} on $1"
+        no_branches_msg="${no_branches_msg} on ${remote}"
+        delete_branches_msg="${delete_branches_msg} on ${remote}"
     fi
 
 
@@ -88,7 +90,7 @@ main(){
         print-branches $branches
         echo
         echo "Would have skipped these branches: "
-        print-branches $(skipped $@ | tr ',' ' ')
+        print-branches $(skipped $skip | tr ',' ' ')
     else
         echo "$delete_branches_msg"
         print-branches $branches
@@ -96,7 +98,7 @@ main(){
         echo "Pausing for 2 seconds ... Press Ctrl-C to quit"
         sleep 2
 
-        if [[ $1 == "--local" ]];then
+        if [[ -n $local ]];then
             git branch -d $branches
         else 
             git push --no-verify --delete $1 $branches
@@ -104,11 +106,25 @@ main(){
     fi
 }
 
-if [[ $# > 0 ]]; then
+usage(){
+    $0 --help 
+    exit 1
+}
+
+if [[ -n $local && -n $remote ]]; then
+    /bin/echo -e "\n ERROR: Can\'t specify both remote and local options!\n"
+    usage
+fi
+
+if [[ ! -n $local && ! -n $remote ]]; then
+    /bin/echo -e "\n ERROR: Need to specify either remote or local option!\n"
+    usage
+fi
+
+if [[ -n $local || -n $remote ]]; then
     main "$@"
 else
     usage
-    exit 1
 fi
 
 # vim: set ft=sh
