la til functions

diff --git a/generelt-oppsett/bash.d/bash_functions b/generelt-oppsett/bash.d/bash_functions
--- a/generelt-oppsett/bash.d/bash_functions
+++ b/generelt-oppsett/bash.d/bash_functions
@@ -1,3 +1,54 @@
+function test() {
+        [[ "$1" == "$2" ]] && echo "OK" || echo "ERROR" $1 $2
+}
+
+function debug() {
+        [[ -n $DEBUG ]] && echo $@ >/dev/stderr
+}
+
+
+# Needed? You can just $(ls $( echo $(echo $(echo /bin/ls)))) 
+
+# Purpose: Easily nest multiple expansions without too much escaping
+# Example usage: Nest expansion of two which statements with a ls
+#        $ left_nested ls which "which javac"
+#        /usr/lib/jdk/java-1.7.0/bin/javac
+function nested_expansion() {
+        res="" 
+        let i=$#
+
+        while (( $i > 0 )); do
+                res=$(eval '$'$i $res);
+                debug $res
+                let i=$i-1;
+        done
+        echo $res
+}
+
+#test
+#test $(nested_expansion "echo 4") 4
+#test $(nested_expansion echo "echo 4") 4
+#test $(nested_expansion ls "echo /dev/zero*") "/dev/zero"
+
+
+# Dereference variables
+# Example:
+#       $ a=b b=c c=d d=e e=blah
+#       $ deref 3 a res; echo "$res"
+#       d
+#       $ deref 5 a res; echo "$res"
+#       blah
+# @see http://unix.stackexchange.com/questions/68042/double-and-triple-substitution-in-bash-and-zsh
+deref() {
+        if [ "$1" -le 0 ]; then
+                eval "$3=\$2"
+        else
+                eval "deref $(($1 - 1)) \"\${$2}\" \"\$3\""
+        fi
+}
+
+# vim: syntax=sh
+
 function set_bilde_tid
 {
     if [ "$1" == "" ]; then
